language: swift
osx_image: xcode11.3.1

env:
  matrix:
   - DESTINATION="platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max"
before_script: cd Texstyle

script:
   - xcodebuild clean test -project Texstyle.xcodeproj -scheme Texstyle -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
   
after_success:
  - bash <(curl -s https://codecov.io/bash)
